version: '3.9'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todolist
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:14-alpine'
    container_name: db
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=todolist-postgres
      - POSTGRES_PASSWORD=todolist-password
      - POSTGRES_DB=todolist